# Generated by Django 4.1.2 on 2022-10-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='username',
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
